src/Entity/MembreEglise.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use App\Repository\MembreEgliseRepository;
use Symfony\Component\Validator\Constraints as Assert; 

/**
 * @ORM\Entity(repositoryClass=MembreEgliseRepository::class)
 */
class MembreEglise
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nom;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $postnom;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $prenom;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $fonctionAssumee;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $sexe;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $EtatCivil;

    /**
     * @ORM\Column(type="integer", nullable=true)
     * @Assert\Length(min="9",minMessage="un numero valide doit avoir au moins 9 chiffres")
     */
    private $telephone;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $adresseAvenue;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $adresseNumero;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $adresseQuartier;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $adresseCommune;

    /**
     * @ORM\Column(type="datetime")
     */
    private $dateEnregistrement;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPostnom(): ?string
    {
        return $this->postnom;
    }

    public function setPostnom(string $postnom): self
    {
        $this->postnom = $postnom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): self
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getFonctionAssumee(): ?string
    {
        return $this->fonctionAssumee;
    }

    public function setFonctionAssumee(string $fonctionAssumee): self
    {
        $this->fonctionAssumee = $fonctionAssumee;

        return $this;
    }

    public function getSexe(): ?string
    {
        return $this->sexe;
    }

    public function setSexe(string $sexe): self
    {
        $this->sexe = $sexe;

        return $this;
    }

    public function getEtatCivil(): ?string
    {
        return $this->EtatCivil;
    }

    public function setEtatCivil(string $EtatCivil): self
    {
        $this->EtatCivil = $EtatCivil;

        return $this;
    }

    public function getTelephone(): ?int
    {
        return $this->telephone;
    }

    public function setTelephone(?int $telephone): self
    {
        $this->telephone = $telephone;

        return $this;
    }

    public function getAdresseAvenue(): ?string
    {
        return $this->adresseAvenue;
    }

    public function setAdresseAvenue(string $adresseAvenue): self
    {
        $this->adresseAvenue = $adresseAvenue;

        return $this;
    }

    public function getAdresseNumero(): ?string
    {
        return $this->adresseNumero;
    }

    public function setAdresseNumero(string $adresseNumero): self
    {
        $this->adresseNumero = $adresseNumero;

        return $this;
    }

    public function getAdresseQuartier(): ?string
    {
        return $this->adresseQuartier;
    }

    public function setAdresseQuartier(string $adresseQuartier): self
    {
        $this->adresseQuartier = $adresseQuartier;

        return $this;
    }

    public function getAdresseCommune(): ?string
    {
        return $this->adresseCommune;
    }

    public function setAdresseCommune(string $adresseCommune): self
    {
        $this->adresseCommune = $adresseCommune;

        return $this;
    }

    public function getDateEnregistrement(): ?\DateTimeInterface
    {
        return $this->dateEnregistrement;
    }

    public function setDateEnregistrement(\DateTimeInterface $dateEnregistrement): self
    {
        $this->dateEnregistrement = $dateEnregistrement;

        return $this;
    }
}

src/Form/FormulaireEnregistrementType.php
<?php

namespace App\Form;

use App\Entity\MembreEglise;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class FormulaireEnregistrementType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('nom')
            ->add('postnom')
            ->add('prenom')
            ->add('fonctionAssumee')
            ->add('sexe')
            ->add('EtatCivil')
            ->add('telephone')
            ->add('adresseAvenue')
            ->add('adresseNumero')
            ->add('adresseQuartier')
            ->add('adresseCommune')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => MembreEglise::class,
        ]);
    }
}

src/Controller/GestionMembresController.php
<?php

namespace App\Controller;

use App\Entity\MembreEglise;
use Doctrine\Persistence\ObjectManager;
use App\Form\FormulaireEnregistrementType;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class GestionMembresController extends AbstractController
{

    /**
     * @Route("/", name="home")
     */
    public function home()
    {
        return $this->render('gestion_membres/acceuil.html.twig');
    }

    /**
     * @Route("/gestion/membres/Apropos", name="page_apropos")
     */
    public function apropos()
    {
        return $this->render('gestion_membres/apropos.html.twig');
    }

    /**
     * @Route("/gestion/membres/Liste", name="liste_membre")
     */
    public function showMembres()
    {
        $repos = $this->getDoctrine()->getRepository(MembreEglise::class);

        $membres = $repos->findAll();

        return $this->render('gestion_membres/liste.html.twig',[
            'membres' => $membres
        ]);
    }

    /**
     * @Route("/gestion/membres/Formulaire", name="form_enregistrement")
     * @Route("/gestion/membres/edit/{id}", name="edit_membre" )
     */
    public function enregistrerEtUpdateMembres(MembreEglise $membre=null, Request $request, ObjectManager $manager)
    {
        if(!$membre){
            $membre = new MembreEglise();
        }

        $formulaire = $this->createForm(FormulaireEnregistrementType::class, $membre);
        $formulaire -> handleRequest($request);

        if ($formulaire -> isSubmitted() && $formulaire -> isvalid()){
            $membre -> setDateEnregistrement(new \DateTime());

            $manager -> persist($membre);
            $manager -> flush();

            return $this -> redirectToRoute('liste_membre',[
                'id'=>$membre->getId()]);

        }
        return $this->render('gestion_membres/formulaire.html.twig',[
            'formulaire' => $formulaire -> createView(),
            'editMode' => $membre -> getId() !== NULL
        ]);
    }

    /**
     * @Route("/gestion/membres/delete/{id}", name="delete_membre" )
     */
    public function supprimer(MembreEglise $membre, ObjectManager $manager)
    {
        
        $manager -> remove($membre);
        $manager -> flush(); 

        return $this -> redirectToRoute('liste_membre');
    }

}

templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Gestion de membres{% endblock %}</title>
        <link rel="stylesheet" href="https://bootswatch.com/4/flatly/bootstrap.min.css">
        <link rel="stylesheet" href="/css/bootstrap.min.css">
        <link rel="stylesheet" href="/css/style.css">
        {% block stylesheets %}{% endblock %}
    </head>
    <body>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="{{ path("home") }}">JCE</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse"  data-target="#navbarColor03"
             aria-controls="navbarColor03" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarColor03">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item active">
                        <a class="nav-link" href="{{ path("home") }}">Accueil<span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ path("form_enregistrement") }}">Formulaire</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ path("liste_membre") }}">Liste</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ path("page_apropos") }}">A propos</a>
                    </li>
                </ul>
            </div>
        </nav>
        <div class="container">
            {% block body %}{% endblock %}
        </div>
        
        {% block javascripts %}
            <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
            <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
        {% endblock %}
    </body>
</html>

templates/gestion_membres/acceuil.html.twig
{% extends 'base.html.twig' %}
{% block body %}
    <div class="row">
          <div class="col-lg-12">
            <h2 class="text-center">Bienvenu(e) dans notre site</h2>
          </div>
          <div class="col-lg-12">
            <p class="text-justify">
              <img src="{{ asset('/images/Bible_30px.png') }}"><strong>LA CRÉATION</strong>, Né 9:6 ; Ps 124:8 ; Jr 32:17 ;
               Jr 10:12 ; Rm 1:20 ; Ap 4:11 ; Jn 1:1-3
               1 Au commencement, Dieu créa les cieux et la terre. 
               Ps 104:2 ; Es 45:72 La terre était informe et vide: il y avait des ténèbres à la 
               surface de l'abîme, et l'esprit de Dieu se mouvait au-dessus des eaux. 3 Dieu dit: 
               Que la lumière soit! Et la lumière fut. 4 Dieu vit que la lumière était bonne; et 
               Dieu sépara la lumière d'avec les ténèbres. 5 Dieu appela la lumière jour, et il 
               appela les ténèbres nuit. Ainsi, il y eut un soir, et il y eut un matin: ce fut le
                premier jour. Ps 104:2-3 ; Ps 19:2 6 Dieu dit: Qu'il y ait une étendue entre les 
                eaux, et qu'elle sépare les eaux d'avec les eaux. 7 Et Dieu fit l'étendue, et il
                sépara les eaux qui sont au-dessous de l'étendue d'avec les eaux qui sont au-dessus
                de l'étendue. Et cela fut ainsi. 8 Dieu appela l'étendue ciel. Ainsi, il y eut un soir,
                et il y eut un matin: ce fut le second jour. 
            </p>
            
          </div>
          <div class="col-lg-3">
            <P><img src="{{ asset('/images/Calendar_20px.png') }}"> NOS PROGRAMMES</P>
            <p>
             <strong>Mardi:</strong> culte d'enseignement<br>
             <strong>Jeudi:</strong> culte d'intercession<br>
             <strong>Dimanche:</strong> culte d'adoration<br>
            </p>
          </div>
          <div class="col-lg-3">
            <P><img src="{{ asset('/images/Clock_20px.png') }}"> HEURES DE CULTE</P>
            <p>
             <strong>Mardi:</strong> 17h30' - 19h30'<br>
             <strong>Jeudi:</strong> 17h30' - 19h30'<br>
             <strong>Dimanche:</strong> 09h30' - 12h30'<br>
            </p>

          </div>
          <div class="col-lg-3">
            <P><img src="{{ asset('/images/Lecturer_20px.png') }}"> MODERATEURS</P>
            <p>
             <strong>Mardi:</strong> Fr. Nsingi<br>
             <strong>Jeudi:</strong> Fr. Merveille<br>
             <strong>Dimanche:</strong> Fr. Gaby<br>
            </p>

          </div>
          <div class="col-lg-3">
            <P><img src="{{ asset('/images/Music_20px.png') }}"> ORCHESTRES</P>
            <p>
             <strong>Mardi:</strong> Heritiers de la promessse<br>
             <strong>Jeudi:</strong> Elus de Dieu<br>
             <strong>Dimanche:</strong> Femmes de distinction<br>
            </p>
          </div>
          <div class="col-lg-12">
            <P class="text-center"><img src="{{ asset('/images/Facebook_25px.png') }}"> Eglise le camp de l'eternel</P>
          </div>
    </div>
          
{% endblock %}

templates/gestion_membres/apropos.html.twig
{% extends 'base.html.twig' %}
{% block body %}
    <div class="row">
          <div class="col-lg-12 mr-auto ml-auto" >
            <p class="text-center"><img src="{{ asset('/images/maphoto1.jpg') }}"></p>
            <p class="text-center"><strong>Gloria MAKIESE</strong>, fullstack web developpeur</p>
          </div>
         
          <div class="col-lg-12 text-justify">
            <p> Ce present site est un site de gestion de membres d'une église en ligne, il a un
             menu constitué de 4 pages, dont la premiere est la page d'acceuil permettant d'afficher
             le programme de l'église, la deuxieme est une page ayant un formulaire pemettant de gerer 
             les membres de l'église (ajouter, modifier et supprimer), la troisieme permet de lister les
             membres enregistrés dans la base de données et la quatrieme c'est l'à propos. </p>
          </div>
          <div class="col-lg-2 mx-auto">
            <p><img src="{{ asset('/images/Facebook_25px.png') }}"> Gloria Makiese</p>
          </div>
          <div class="col-lg-2 mx-auto">
            <p><img src="{{ asset('/images/Twitter_25px.png') }}"> Gloria Makiese</p>
          </div>
          <div class="col-lg-2 mx-auto">
            <p><img src="{{ asset('/images/LinkedIn_25px.png') }}"> Gloria Makiese</p>
          </div>
          <div class="col-lg-2 mx-auto">
            <p><img src="{{ asset('/images/GitHub_25px.png') }}"> Gloria Makiese</p>
          </div>
          <div class="col-lg-12 text-center">
            <hr>
            <p>&copy;copyright 2020 | designed by GM Design</p>
          </div>
          
        </div>
{% endblock %}

templates/gestion_membres/formulaire.html.twig
{% extends 'base.html.twig' %}
{% block body %}
    <h2 class="text-center">Enregistrement membre</h2>
    {{ form_start(formulaire) }}
    <div class="col-lg-6 ml-auto mr-auto">
        <div class="form-group">
            {{ form_row(formulaire.nom, {'attr': {'placeholder': "Nom", 'class': "form-control"}}) }}
        </div>
        <div class="form-group">
            {{ form_row(formulaire.postnom, {'attr': {'placeholder': "Postnom", 'class': "form-control"}}) }}
        </div>
        <div class="form-group">
            {{ form_row(formulaire.prenom, {'attr': {'placeholder': "Prenom", 'class': "form-control"}}) }}
        </div>
        <div class="form-group">
            {{ form_row(formulaire.fonctionAssumee, {'attr': {'placeholder': "Quelle est la fonction que vous occupez à l'église!!!", 'class': "form-control "}}) }}
        </div>
        <div class="form-group">
            {{ form_row(formulaire.sexe, {'attr': {'placeholder': "Sexe", 'class': "form-control "}}) }}
        </div>
        <div class="form-group">
            {{ form_row(formulaire.EtatCivil, {'attr': {'placeholder': "Etat civil", 'class': "form-control "}}) }}
        </div>
        <div class="form-group">
            {{ form_row(formulaire.telephone, {'attr': {'placeholder': "Téléphone", 'class': "form-control "}}) }}
        </div>
        <div class="form-group">
            {{ form_row(formulaire.adresseAvenue, {'attr': {'placeholder': "Avenue", 'class': "form-control "}}) }}
        </div>
        <div class="form-group">
            {{ form_row(formulaire.adresseNumero, {'attr': {'placeholder': "Numero", 'class': "form-control "}}) }}
        </div>
        <div class="form-group">
            {{ form_row(formulaire.adresseQuartier, {'attr': {'placeholder': "Quartier", 'class': "form-control "}}) }}
        </div>
        <div class="form-group">
            {{ form_row(formulaire.adresseCommune, {'attr': {'placeholder': "Commune", 'class': "form-control "}}) }}
        </div>
        <button type="submit" class="btn btn-success">
            {% if editMode %}
                Modifier membre
            {% else %}
                Ajouter membre
            {% endif %}
        </button>
    </div>
    {{ form_end(formulaire) }}
{% endblock %}

templates/gestion_membres/index.html.twig
{% extends 'base.html.twig' %}

{% endblock %}

templates/gestion_membres/liste.html.twig
{% extends 'base.html.twig' %}
{% block body %}
    <h2 class="text-center"> la liste de membres effectifs</h2>
    <div class="table-responsive">
         <table class="table table-striped  mx-auto" >
          <thead>
            <tr class="text-center"><th>Nom </th><th>Postnom </th><th>Prenom</th>
                <th>fonction</th><th>sexe</th><th>Etat-civil</th>
                <th>Telephone</th><th>Date d'enregistrement</th><th>Avenue</th>
                <th>numero</th><th>quartier</th><th>commune</th><th>actions</th></tr>
          </thead>
          <tbody>
            {% for membre in membres %}
            <tr class="text-center"><td>{{ membre.nom }}</td><td>{{ membre.postnom }}</td><td>{{ membre.prenom }}</td>
              <td>{{ membre.fonctionAssumee }}</td><td>{{ membre.sexe }}</td><td>{{ membre.etatCivil }}</td>
              <td>{{ membre.telephone }}</td><td>{{ membre.dateEnregistrement | date('d/m/Y') }}</td><td>{{ membre.adresseAvenue }}</td>
              <td>{{ membre.adresseNumero }}</td><td>{{ membre.adresseQuartier }}</td><td>{{ membre.adresseCommune }}</td>
              <td>
                <a href="{{ path('edit_membre',{"id": membre.id}) }}" class="btn btn-warning" onclick="return confirm('voulez-vous vraiment supprimer ce 
                            membre de votre base de données???')">modifier</a>
              </td>
              <td>
                <a href="{{ path('delete_membre',{"id": membre.id}) }}" class="btn btn-danger" onclick="return confirm('voulez-vous vraiment supprimer ce 
                            membre de votre base de données???')">supprimer</a>
              </td>
            </tr>

          {% endfor %}

          </tbody>
	        
        
    </table>
    </div>
{% endblock %}